### ISSUE TITLE
Help switch not working in 223 build

### ISSUE THREAD

**Issue by dkrotil** [tdharris/dsapp#67]
In build 220 I was able look on possible command line switches with dsapp --help, in build 223 is this not working.

**Comment by snielson** [comment]
It still displays, but you have to scroll up now, as it runs a linux 'clear'.
The problem seems to be when I added the EXIT code to my trap call, which would run a clean up function. That function happen to have the 'clear' command built in.

I'm removing the EXIT from the current trap, and create another function to only do some mild clean up (removing the ~/.pgpass if 'True')

Removing 'EXIT' from line 81 should fix this until then.

**Comment by snielson** [comment]
New cleanup_exit function built into v224. No longer clears the screen on EXIT
